application: handsign-gen
version: dev
runtime: php
api_version: 1
threadsafe: yes

inbound_services:
- warmup

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: static/\1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: script/\1
